# AUTOGENERATED! DO NOT EDIT! File to edit: ../../nbs/00_test_core.ipynb.

# %% auto 0
__all__ = ['TestNotebookParser']

# %% ../../nbs/00_test_core.ipynb 1
from ..core import *

# %% ../../nbs/01_core.ipynb 5
import unittest

class TestNotebookParser(unittest.TestCase):
    
    def test_repo_string(self):
        notebook_parser = NotebookParser()
        self.assertEqual(notebook_parser.repo_string, 'nbdev_unittest')